sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-109.pdf --upload --lsstdoc DMTN-109.tex --env=travis --ltd-product dmtn-109"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "pLC2rTv3b/OPacLKnJaPDy76hDD0ZUnpaD3tc7uSKOtdzrBo+1oUgfK5RHgoBoOLlD6/e8K0UDO4Rgam96Sivt8mjuaP6dnqIpKmdoUPa7pLmW8Ysm41RPVmU6unbka92dGQTKeyW9G5g2MDOXSXqoUgpCIAyWprAJLrH3NX5DlPMHtd/mwdZsBiBCTHbGD0nwkrIeYpqzT2+rRw6EigeLxbl0kU06h1bHqcbUtz3Vq7W2J5DFh9f4NnpDOOmFuo3pHsPSUeiNgTggvt67WTDERLq2ZVJAvN6B2qMmEf9Fs09OZVL0TR3MsY85GBXeYrVRWKMgf7UbBNcOSI4sYnjFbXSU0MUKd0Lns1FHZl4dTKRaIjtSZUT9+jGia0J/MZoqzJGzv1U6NuYJVYv0J4glvIfvR59LgMr17oj/zsY5fqKcuGvV3WAzwkSrVzHkGjOMv3F3Yafix7IPTdiKnyPoxtS0H5LxWmVKhPhaS9nDJ9H5zbYJEpzPHlo5ae2UbVgGRX9rp3RxfFSVLMWvRJF+BVNIiZNwSX5wczudR6N3TpeHO30bCswcpan45jY6Uasm8QHfIaE6MPHk0zDaa0vPoOZr+++OdHgDNC0tCcLUxvSTQKe6T0HloL/KpkAqEp6ZRx4w+A13dCTu18YDce1ChF+qJL+H/vvM9vtDZRId0="
    - secure: "acpTJo09MpXYMC2fV0ym4QeTp0AupWjXMutRt4X5+bnsSyW4thfrXVNEQg+YeWlX2IutfpoLgAVyPWlaGnWa4EI8saYvjPNruK3HeLzKpT/IOXaqATuD6KVI8Uybwlzde/83UC3kucFHy+01axffm8SDMvn5RQeMtXi3AQUm84XH4rWXEocpH26JuQ0D61BpjiH3DwR2sVRoJXIgKUP9DoZmccFGAjLNrKjGxlJ5fUFhrF/Q4f9oxkPepEH1UDTLmiyr6Mfv6gbPukPfJSmUuW2Ck05i7FlDop1pdDJMaRorzbUHaDQ8/3dI/HOqMKpurn1HIZfTbz9EREVM/P3o8ihnXe68DJVV2Up1/NQlwTUQhqDQQqcpdH6d1Quhp+pnIjy5dJe1ptKGS30w30V3sVmXdOzSWmRqVE0vDvVcObjHg84WbazgVzEtleDfUevD/s824ARpIf+OJxEFpmeCNKB5cdsRPDCJWH3xBjeWsnfOvlcw7VlT3hG1Vi2QGGDVuEwkVJ7k00krtEKXj+ITdiC5Ko9ArDdI8MZ4qcWTKTahBoe/i5gyCcCYPFhHbmTUop9fVWBKVnu8DxBi1L9Pm6LhgtOBM8PAsh1ek02a4eA6yYQId+MQLCC+tfXMBACnfYDFwRoE4HEokSpwoSoop3yNKUuAMP6AypJcXtY0gbc="
